name: renew_and_deploy_ssl_cert

on:
  schedule:
    - cron: "0 0 1 * *" # Run monthly on the first day at midnight
  workflow_dispatch:

jobs:
  renew-deploy-cert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Certbot
        run: sudo apt-get update && sudo apt-get install -y certbot

      - name: Obtain Let's Encrypt Wildcard Certificate
        env:
          EMAIL: ${{ secrets.HEROKU_USER_EMAIL }}
          DOMAIN: ${{ secrets.HEROKU_APP_DOMAIN }}
          NAMECHEAP_API_KEY: ${{ secrets.NAMECHEAP_API_KEY }}
          NAMECHEAP_API_USER: ${{ secrets.NAMECHEAP_API_USER }}
          NAMECHEAP_CLIENT_IP: ${{ secrets.NAMECHEAP_API_IP }}
        run: |
          sudo certbot certonly \
            --manual \
            --preferred-challenges=dns \
            --email $EMAIL \
            --server https://acme-v02.api.letsencrypt.org/directory \
            --agree-tos -d "$DOMAIN" \
            --manual-public-ip-logging-ok \
            --non-interactive \
            --manual-auth-hook "${{ github.workspace }}/hooks/manual-auth-hook.sh" \
            --manual-cleanup-hook "${{ github.workspace }}/hooks/manual-cleanup-hook.sh"

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Upload certificate to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          DOMAIN: ${{ secrets.HEROKU_APP_DOMAIN }}
        run: |
          CERT_PATH="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
          KEY_PATH="/etc/letsencrypt/live/$DOMAIN/privkey.pem"
          echo $HEROKU_API_KEY | heroku auth:token
          heroku certs:add $CERT_PATH $KEY_PATH -a $HEROKU_APP_NAME
